### ISSUE TITLE
Add `/join` command

### ISSUE THREAD

**Issue by Markusplay** [srkpi/hedgehog-bot#1]
Bot should as user to fill next fields:
1. ПІБ
2. Як до тебе звертатись?
3. Твоя група і факультет/інститут? Українською. У форматі ХХ-00, АБВ
4. Як часто буваєш на КПІ? Розуміти місцезнаходження команди важливо для планування заходів
Option 1. Легко можу приїхати на КПІ або часто там буваю
Option 2. Не часто зможу бути на КПІ
Option 3. Працюватиму лише дистанційно

5. У які департаменти/служби найбільше хотів/ла би?
Почитай [статтю](https://www.hashtap.com/@sr_kpi/%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D1%81%D1%8C%D0%BA%D0%B0-%D1%80%D0%B0%D0%B4%D0%B0-%D0%BA%D0%BF%D1%96-Zdg3640XZLl6) про підрозділи Студради КПІ.
Обирай не більше 2 департаментів/служб.
Buttons with departments and services. User can pick one or two options. No more.
6. Дата народження. Формат dd/mm/yyyy
7. Чи був у тебе досвід у волонтерстві раніше?
Тут розкажи про будь-який досвід волонтерства та організації проектів, якщо маєш його. 
8. Твоя мотивація бути в команді Студради КПІ.
Напиши, чому хочеш доєднатись до Студради. Будь ласка, не пиши мотивацію одним реченням, краще розпиши більш розгорнуто. 
9. Даю згоду на обробку персольних даних. Button with ✅.
On success, the bot should send a message with filled fields to a specific chat.

**Comment by ETLARIS** [comment]
Done.
